# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\tMapReduce\"$\n\nJobRequest\x12\x16\n\x0einput_location\x18\x01 \x01(\t\">\n\x0bJobResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x0e\n\x06job_id\x18\x03 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"4\n\x11JobStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"G\n\x1cMapperCompletionNotification\x12\x12\n\ninput_file\x18\x01 \x01(\t\x12\x13\n\x0boutput_file\x18\x02 \x01(\t\"4\n\x1dReducerCompletionNotification\x12\x13\n\x0boutput_file\x18\x01 \x01(\t\"\'\n\x14NotificationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe6\x02\n\x12\x43oordinatorService\x12\x39\n\x08StartJob\x12\x15.MapReduce.JobRequest\x1a\x16.MapReduce.JobResponse\x12K\n\x0e\x43heckJobStatus\x12\x1b.MapReduce.JobStatusRequest\x1a\x1c.MapReduce.JobStatusResponse\x12\x62\n\x16NotifyMapperCompletion\x12\'.MapReduce.MapperCompletionNotification\x1a\x1f.MapReduce.NotificationResponse\x12\x64\n\x17NotifyReducerCompletion\x12(.MapReduce.ReducerCompletionNotification\x1a\x1f.MapReduce.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOBREQUEST']._serialized_start=32
  _globals['_JOBREQUEST']._serialized_end=68
  _globals['_JOBRESPONSE']._serialized_start=70
  _globals['_JOBRESPONSE']._serialized_end=132
  _globals['_JOBSTATUSREQUEST']._serialized_start=134
  _globals['_JOBSTATUSREQUEST']._serialized_end=168
  _globals['_JOBSTATUSRESPONSE']._serialized_start=170
  _globals['_JOBSTATUSRESPONSE']._serialized_end=222
  _globals['_MAPPERCOMPLETIONNOTIFICATION']._serialized_start=224
  _globals['_MAPPERCOMPLETIONNOTIFICATION']._serialized_end=295
  _globals['_REDUCERCOMPLETIONNOTIFICATION']._serialized_start=297
  _globals['_REDUCERCOMPLETIONNOTIFICATION']._serialized_end=349
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=351
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=390
  _globals['_COORDINATORSERVICE']._serialized_start=393
  _globals['_COORDINATORSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
