# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import heartbeat_pb2 as heartbeat__pb2


class HeartbeatServiceStub(object):
    """The heartbeat service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHeartbeat = channel.unary_unary(
                '/heartbeat.HeartbeatService/SendHeartbeat',
                request_serializer=heartbeat__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=heartbeat__pb2.HeartbeatResponse.FromString,
                )


class HeartbeatServiceServicer(object):
    """The heartbeat service definition.
    """

    def SendHeartbeat(self, request, context):
        """Sends a heartbeat signal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeartbeatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=heartbeat__pb2.HeartbeatRequest.FromString,
                    response_serializer=heartbeat__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heartbeat.HeartbeatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HeartbeatService(object):
    """The heartbeat service definition.
    """

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/heartbeat.HeartbeatService/SendHeartbeat',
            heartbeat__pb2.HeartbeatRequest.SerializeToString,
            heartbeat__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
